/*
 * generated by Xtext
 */
package org.xtext.DOE.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.DOE.ui.internal.ExperimentOntologyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExperimentOntologyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ExperimentOntologyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ExperimentOntologyActivator.getInstance().getInjector(ExperimentOntologyActivator.ORG_XTEXT_DOE_EXPERIMENTONTOLOGY);
	}
	
}
