/*
 * generated by Xtext
 */
package org.xtext.DOE;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExperimentOntologyUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.DOE.ui.internal.ExperimentOntologyActivator.getInstance().getInjector("org.xtext.DOE.ExperimentOntology");
	}
	
}
