/*
 * generated by Xtext
 */
package org.xtext.DOE.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.DOE.services.ExperimentOntologyGrammarAccess;

public class ExperimentOntologyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExperimentOntologyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.DOE.parser.antlr.internal.InternalExperimentOntologyParser createParser(XtextTokenStream stream) {
		return new org.xtext.DOE.parser.antlr.internal.InternalExperimentOntologyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ExperimentOntologyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExperimentOntologyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
