/*
 * generated by Xtext
 */
package org.xtext.DOE.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractExperimentOntologyValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.xtext.DOE.experimentOntology.ExperimentOntologyPackage.eINSTANCE);
		return result;
	}
}
