/*
 * generated by Xtext
 */
package org.xtext.DOE;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ExperimentOntologyStandaloneSetup extends ExperimentOntologyStandaloneSetupGenerated{

	public static void doSetup() {
		new ExperimentOntologyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

