/*
 * generated by Xtext
 */
package org.xtext.DOE;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExperimentOntologyRuntimeModule extends org.xtext.DOE.AbstractExperimentOntologyRuntimeModule {

}
