/**
 * generated by Xtext
 */
package org.xtext.DOE.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterators;
import java.util.Iterator;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.DOE.experimentOntology.Design;
import org.xtext.DOE.experimentOntology.Experiment;
import org.xtext.DOE.experimentOntology.Factor;
import org.xtext.DOE.experimentOntology.FactorLevels;
import org.xtext.DOE.experimentOntology.GuardCondition;
import org.xtext.DOE.experimentOntology.IndependentVariables;
import org.xtext.DOE.experimentOntology.Mechanism;
import org.xtext.DOE.experimentOntology.ModelSection;
import org.xtext.DOE.experimentOntology.Reaction;
import org.xtext.DOE.experimentOntology.Values;
import org.xtext.DOE.experimentOntology.Variables;
import org.xtext.DOE.experimentOntology.properties;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class ExperimentOntologyGenerator implements IGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<ModelSection> _filter = Iterators.<ModelSection>filter(_allContents, ModelSection.class);
    ModelSection _head = IteratorExtensions.<ModelSection>head(_filter);
    CharSequence _iSHCProperties = this.toISHCProperties(_head);
    fsa.generateFile("ishc.properties", _iSHCProperties);
    TreeIterator<EObject> _allContents_1 = resource.getAllContents();
    Iterator<ModelSection> _filter_1 = Iterators.<ModelSection>filter(_allContents_1, ModelSection.class);
    ModelSection _head_1 = IteratorExtensions.<ModelSection>head(_filter_1);
    TreeIterator<EObject> _allContents_2 = resource.getAllContents();
    Iterator<Experiment> _filter_2 = Iterators.<Experiment>filter(_allContents_2, Experiment.class);
    Experiment _head_2 = IteratorExtensions.<Experiment>head(_filter_2);
    CharSequence _deliveryProperties = this.toDeliveryProperties(_head_1, _head_2);
    fsa.generateFile("delivery.properties", _deliveryProperties);
    TreeIterator<EObject> _allContents_3 = resource.getAllContents();
    Iterator<ModelSection> _filter_3 = Iterators.<ModelSection>filter(_allContents_3, ModelSection.class);
    ModelSection _head_3 = IteratorExtensions.<ModelSection>head(_filter_3);
    CharSequence _kupfferCell = this.toKupfferCell(_head_3);
    fsa.generateFile("KupfferCell.java", _kupfferCell);
    TreeIterator<EObject> _allContents_4 = resource.getAllContents();
    Iterator<ModelSection> _filter_4 = Iterators.<ModelSection>filter(_allContents_4, ModelSection.class);
    ModelSection _head_4 = IteratorExtensions.<ModelSection>head(_filter_4);
    CharSequence _hepatocyte = this.toHepatocyte(_head_4);
    fsa.generateFile("Hepatocyte.java", _hepatocyte);
  }
  
  public CharSequence toISHCProperties(final ModelSection m) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# model parameters");
    _builder.newLine();
    _builder.append("stepsPerCycle = 1");
    _builder.newLine();
    _builder.append("# component parameters");
    _builder.newLine();
    {
      EList<Factor> _parameters = m.getParameters();
      for(final Factor factor : _parameters) {
        {
          boolean _notEquals = (!Objects.equal(factor, null));
          if (_notEquals) {
            {
              Values _factorValue = factor.getFactorValue();
              boolean _notEquals_1 = (!Objects.equal(_factorValue, null));
              if (_notEquals_1) {
                {
                  Values _factorValue_1 = factor.getFactorValue();
                  String _function = _factorValue_1.getFunction();
                  boolean _notEquals_2 = (!Objects.equal(_function, null));
                  if (_notEquals_2) {
                    String _factorName = factor.getFactorName();
                    _builder.append(_factorName, "");
                    _builder.append(" = ");
                    Values _factorValue_2 = factor.getFactorValue();
                    String _function_1 = _factorValue_2.getFunction();
                    _builder.append(_function_1, "");
                    _builder.newLineIfNotEmpty();
                  } else {
                    Values _factorValue_3 = factor.getFactorValue();
                    String _fVal = _factorValue_3.getFVal();
                    boolean _notEquals_3 = (!Objects.equal(_fVal, null));
                    if (_notEquals_3) {
                      String _factorName_1 = factor.getFactorName();
                      _builder.append(_factorName_1, "");
                      _builder.append(" = ");
                      Values _factorValue_4 = factor.getFactorValue();
                      String _fVal_1 = _factorValue_4.getFVal();
                      _builder.append(_fVal_1, "");
                      _builder.newLineIfNotEmpty();
                    } else {
                      Values _factorValue_5 = factor.getFactorValue();
                      String _fvalue = _factorValue_5.getFvalue();
                      boolean _notEquals_4 = (!Objects.equal(_fvalue, null));
                      if (_notEquals_4) {
                        String _factorName_2 = factor.getFactorName();
                        _builder.append(_factorName_2, "");
                        _builder.append(" = ");
                        Values _factorValue_6 = factor.getFactorValue();
                        String _fvalue_1 = _factorValue_6.getFvalue();
                        _builder.append(_fvalue_1, "");
                        _builder.newLineIfNotEmpty();
                      } else {
                        Values _factorValue_7 = factor.getFactorValue();
                        String _value = _factorValue_7.getValue();
                        boolean _notEquals_5 = (!Objects.equal(_value, null));
                        if (_notEquals_5) {
                          String _factorName_3 = factor.getFactorName();
                          _builder.append(_factorName_3, "");
                          _builder.append(" = ");
                          Values _factorValue_8 = factor.getFactorValue();
                          String _value_1 = _factorValue_8.getValue();
                          _builder.append(_value_1, "");
                          _builder.newLineIfNotEmpty();
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence toDeliveryProperties(final ModelSection m, final Experiment e) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("deliveryType = bolus");
    _builder.newLine();
    _builder.append("useContinualDoseFunction = false");
    _builder.newLine();
    _builder.append("repeatDose = true");
    _builder.newLine();
    _builder.append("infusionStopTime = 120.0");
    _builder.newLine();
    _builder.append("numDoses = 1");
    _builder.newLine();
    _builder.append("time.0 = 1.0");
    _builder.newLine();
    _builder.append("time.1 = 10.0");
    _builder.newLine();
    _builder.append("dose.0.alpha = 2000");
    _builder.newLine();
    _builder.append("dose.0.beta = -1");
    _builder.newLine();
    _builder.append("dose.0.gamma = -2");
    _builder.newLine();
    _builder.append("dose.0.numEntries = 7");
    _builder.newLine();
    int count1 = (-1);
    _builder.newLineIfNotEmpty();
    _builder.append(" ");
    _builder.newLine();
    {
      EList<Factor> _parameters = m.getParameters();
      for(final Factor factor : _parameters) {
        {
          boolean _notEquals = (!Objects.equal(factor, null));
          if (_notEquals) {
            _builder.append("#");
            int _plusPlus = count1++;
            _builder.append(_plusPlus, "");
            _builder.newLineIfNotEmpty();
            {
              EList<properties> _factorProperties = factor.getFactorProperties();
              boolean _notEquals_1 = (!Objects.equal(_factorProperties, null));
              if (_notEquals_1) {
                int count2 = 0;
                _builder.newLineIfNotEmpty();
                {
                  EList<properties> _factorProperties_1 = factor.getFactorProperties();
                  for(final properties p : _factorProperties_1) {
                    _builder.newLine();
                    _builder.append("\t");
                    _builder.newLine();
                    {
                      boolean _or = false;
                      boolean _or_1 = false;
                      boolean _or_2 = false;
                      boolean _or_3 = false;
                      boolean _or_4 = false;
                      boolean _or_5 = false;
                      boolean _or_6 = false;
                      boolean _or_7 = false;
                      String _pName = p.getPName();
                      boolean _equals = _pName.equals("membraneCrossing");
                      if (_equals) {
                        _or_7 = true;
                      } else {
                        String _pName_1 = p.getPName();
                        boolean _equals_1 = _pName_1.equals("bileRatio");
                        _or_7 = _equals_1;
                      }
                      if (_or_7) {
                        _or_6 = true;
                      } else {
                        String _pName_2 = p.getPName();
                        boolean _equals_2 = _pName_2.equals("core2Rim");
                        _or_6 = _equals_2;
                      }
                      if (_or_6) {
                        _or_5 = true;
                      } else {
                        String _pName_3 = p.getPName();
                        boolean _equals_3 = _pName_3.equals("metProbStart");
                        _or_5 = _equals_3;
                      }
                      if (_or_5) {
                        _or_4 = true;
                      } else {
                        String _pName_4 = p.getPName();
                        boolean _equals_4 = _pName_4.equals("metProbFinish");
                        _or_4 = _equals_4;
                      }
                      if (_or_4) {
                        _or_3 = true;
                      } else {
                        String _pName_5 = p.getPName();
                        boolean _equals_5 = _pName_5.equals("metabolites");
                        _or_3 = _equals_5;
                      }
                      if (_or_3) {
                        _or_2 = true;
                      } else {
                        String _pName_6 = p.getPName();
                        boolean _equals_6 = _pName_6.equals("inflammatory");
                        _or_2 = _equals_6;
                      }
                      if (_or_2) {
                        _or_1 = true;
                      } else {
                        String _pName_7 = p.getPName();
                        boolean _equals_7 = _pName_7.equals("pDegrade");
                        _or_1 = _equals_7;
                      }
                      if (_or_1) {
                        _or = true;
                      } else {
                        String _pName_8 = p.getPName();
                        boolean _equals_8 = _pName_8.equals("transportOut");
                        _or = _equals_8;
                      }
                      boolean _not = (!_or);
                      if (_not) {
                        _builder.append("\t");
                        _builder.newLine();
                        {
                          Values _pVal = p.getPVal();
                          String _fVal = _pVal.getFVal();
                          boolean _notEquals_2 = (!Objects.equal(_fVal, null));
                          if (_notEquals_2) {
                            _builder.append("\t");
                            _builder.append("dose.0.solute.");
                            _builder.append(count1, "\t");
                            _builder.append(".");
                            String _pName_9 = p.getPName();
                            _builder.append(_pName_9, "\t");
                            _builder.append(" = ");
                            Values _pVal_1 = p.getPVal();
                            String _fVal_1 = _pVal_1.getFVal();
                            _builder.append(_fVal_1, "\t");
                            _builder.newLineIfNotEmpty();
                          } else {
                            Values _pVal_2 = p.getPVal();
                            String _function = _pVal_2.getFunction();
                            boolean _notEquals_3 = (!Objects.equal(_function, null));
                            if (_notEquals_3) {
                              _builder.append("\t");
                              _builder.append("dose.0.solute.");
                              _builder.append(count1, "\t");
                              _builder.append(".");
                              String _pName_10 = p.getPName();
                              _builder.append(_pName_10, "\t");
                              _builder.append(" = ");
                              Values _pVal_3 = p.getPVal();
                              String _function_1 = _pVal_3.getFunction();
                              _builder.append(_function_1, "\t");
                              _builder.newLineIfNotEmpty();
                            } else {
                              Values _pVal_4 = p.getPVal();
                              String _value = _pVal_4.getValue();
                              boolean _notEquals_4 = (!Objects.equal(_value, null));
                              if (_notEquals_4) {
                                _builder.append("\t");
                                _builder.append("dose.0.solute.");
                                _builder.append(count1, "\t");
                                _builder.append(".");
                                String _pName_11 = p.getPName();
                                _builder.append(_pName_11, "\t");
                                _builder.append(" = ");
                                Values _pVal_5 = p.getPVal();
                                String _value_1 = _pVal_5.getValue();
                                _builder.append(_value_1, "\t");
                                _builder.newLineIfNotEmpty();
                              } else {
                                Values _pVal_6 = p.getPVal();
                                String _fvalue = _pVal_6.getFvalue();
                                boolean _notEquals_5 = (!Objects.equal(_fvalue, null));
                                if (_notEquals_5) {
                                  _builder.append("\t");
                                  _builder.append("dose.0.solute.");
                                  _builder.append(count1, "\t");
                                  _builder.append(".");
                                  String _pName_12 = p.getPName();
                                  _builder.append(_pName_12, "\t");
                                  _builder.append(" = ");
                                  Values _pVal_7 = p.getPVal();
                                  String _fvalue_1 = _pVal_7.getFvalue();
                                  _builder.append(_fvalue_1, "\t");
                                  _builder.newLineIfNotEmpty();
                                }
                              }
                            }
                          }
                        }
                      } else {
                        boolean _or_8 = false;
                        boolean _or_9 = false;
                        boolean _or_10 = false;
                        boolean _or_11 = false;
                        boolean _or_12 = false;
                        String _pName_13 = p.getPName();
                        boolean _equals_9 = _pName_13.equals("bileRatio");
                        if (_equals_9) {
                          _or_12 = true;
                        } else {
                          String _pName_14 = p.getPName();
                          boolean _equals_10 = _pName_14.equals("core2Rim");
                          _or_12 = _equals_10;
                        }
                        if (_or_12) {
                          _or_11 = true;
                        } else {
                          String _pName_15 = p.getPName();
                          boolean _equals_11 = _pName_15.equals("metProbStart");
                          _or_11 = _equals_11;
                        }
                        if (_or_11) {
                          _or_10 = true;
                        } else {
                          String _pName_16 = p.getPName();
                          boolean _equals_12 = _pName_16.equals("metProbFinish");
                          _or_10 = _equals_12;
                        }
                        if (_or_10) {
                          _or_9 = true;
                        } else {
                          String _pName_17 = p.getPName();
                          boolean _equals_13 = _pName_17.equals("inflammatory");
                          _or_9 = _equals_13;
                        }
                        if (_or_9) {
                          _or_8 = true;
                        } else {
                          String _pName_18 = p.getPName();
                          boolean _equals_14 = _pName_18.equals("pDegrade");
                          _or_8 = _equals_14;
                        }
                        if (_or_8) {
                          _builder.append("\t");
                          _builder.append("dose.0.solute.");
                          _builder.append(count1, "\t");
                          _builder.append(".property.");
                          _builder.append(count2, "\t");
                          _builder.append(".key = ");
                          String _pName_19 = p.getPName();
                          _builder.append(_pName_19, "\t");
                          _builder.newLineIfNotEmpty();
                          _builder.append("\t");
                          _builder.append("dose.0.solute.");
                          _builder.append(count1, "\t");
                          _builder.append(".property.");
                          _builder.append(count2, "\t");
                          _builder.append(".type = real");
                          _builder.newLineIfNotEmpty();
                          _builder.append("\t");
                          _builder.newLine();
                          _builder.append("\t");
                          _builder.newLine();
                          {
                            Values _pVal_8 = p.getPVal();
                            String _fVal_2 = _pVal_8.getFVal();
                            boolean _notEquals_6 = (!Objects.equal(_fVal_2, null));
                            if (_notEquals_6) {
                              _builder.append("\t");
                              _builder.append("dose.0.solute.");
                              _builder.append(count1, "\t");
                              _builder.append(".property.");
                              int _plusPlus_1 = count2++;
                              _builder.append(_plusPlus_1, "\t");
                              _builder.append(".val =  ");
                              Values _pVal_9 = p.getPVal();
                              String _fVal_3 = _pVal_9.getFVal();
                              _builder.append(_fVal_3, "\t");
                              _builder.newLineIfNotEmpty();
                            } else {
                              Values _pVal_10 = p.getPVal();
                              String _function_2 = _pVal_10.getFunction();
                              boolean _notEquals_7 = (!Objects.equal(_function_2, null));
                              if (_notEquals_7) {
                                _builder.append("\t");
                                _builder.append("dose.0.solute.");
                                _builder.append(count1, "\t");
                                _builder.append(".property.");
                                int _plusPlus_2 = count2++;
                                _builder.append(_plusPlus_2, "\t");
                                _builder.append(".val =  ");
                                Values _pVal_11 = p.getPVal();
                                String _function_3 = _pVal_11.getFunction();
                                _builder.append(_function_3, "\t");
                                _builder.newLineIfNotEmpty();
                              } else {
                                Values _pVal_12 = p.getPVal();
                                String _value_2 = _pVal_12.getValue();
                                boolean _notEquals_8 = (!Objects.equal(_value_2, null));
                                if (_notEquals_8) {
                                  _builder.append("\t");
                                  _builder.append("dose.0.solute.");
                                  _builder.append(count1, "\t");
                                  _builder.append(".property.");
                                  int _plusPlus_3 = count2++;
                                  _builder.append(_plusPlus_3, "\t");
                                  _builder.append(".val =  ");
                                  Values _pVal_13 = p.getPVal();
                                  String _value_3 = _pVal_13.getValue();
                                  _builder.append(_value_3, "\t");
                                  _builder.newLineIfNotEmpty();
                                } else {
                                  Values _pVal_14 = p.getPVal();
                                  String _fvalue_2 = _pVal_14.getFvalue();
                                  boolean _notEquals_9 = (!Objects.equal(_fvalue_2, null));
                                  if (_notEquals_9) {
                                    _builder.append("\t");
                                    _builder.append("dose.0.solute.");
                                    _builder.append(count1, "\t");
                                    _builder.append(".property.");
                                    int _plusPlus_4 = count2++;
                                    _builder.append(_plusPlus_4, "\t");
                                    _builder.append(".val =  ");
                                    Values _pVal_15 = p.getPVal();
                                    String _fvalue_3 = _pVal_15.getFvalue();
                                    _builder.append(_fvalue_3, "\t");
                                    _builder.newLineIfNotEmpty();
                                  }
                                }
                              }
                            }
                          }
                          _builder.append("\t");
                          _builder.newLine();
                        } else {
                          boolean _or_13 = false;
                          String _pName_20 = p.getPName();
                          boolean _equals_15 = _pName_20.equals("membraneCrossing");
                          if (_equals_15) {
                            _or_13 = true;
                          } else {
                            String _pName_21 = p.getPName();
                            boolean _equals_16 = _pName_21.equals("transportOut");
                            _or_13 = _equals_16;
                          }
                          if (_or_13) {
                            _builder.append("\t");
                            _builder.append("dose.0.solute.");
                            _builder.append(count1, "\t");
                            _builder.append(".property.");
                            _builder.append(count2, "\t");
                            _builder.append(".key = ");
                            String _pName_22 = p.getPName();
                            _builder.append(_pName_22, "\t");
                            _builder.newLineIfNotEmpty();
                            _builder.append("\t");
                            _builder.append("dose.0.solute.");
                            _builder.append(count1, "\t");
                            _builder.append(".property.");
                            _builder.append(count2, "\t");
                            _builder.append(".type = boolean");
                            _builder.newLineIfNotEmpty();
                            _builder.append("\t");
                            _builder.newLine();
                            _builder.append("\t");
                            _builder.newLine();
                            {
                              Values _pVal_16 = p.getPVal();
                              String _fVal_4 = _pVal_16.getFVal();
                              boolean _notEquals_10 = (!Objects.equal(_fVal_4, null));
                              if (_notEquals_10) {
                                _builder.append("\t");
                                _builder.append("dose.0.solute.");
                                _builder.append(count1, "\t");
                                _builder.append(".property.");
                                int _plusPlus_5 = count2++;
                                _builder.append(_plusPlus_5, "\t");
                                _builder.append(".val =  ");
                                Values _pVal_17 = p.getPVal();
                                String _fVal_5 = _pVal_17.getFVal();
                                _builder.append(_fVal_5, "\t");
                                _builder.newLineIfNotEmpty();
                              } else {
                                Values _pVal_18 = p.getPVal();
                                String _function_4 = _pVal_18.getFunction();
                                boolean _notEquals_11 = (!Objects.equal(_function_4, null));
                                if (_notEquals_11) {
                                  _builder.append("\t");
                                  _builder.append("dose.0.solute.");
                                  _builder.append(count1, "\t");
                                  _builder.append(".property.");
                                  int _plusPlus_6 = count2++;
                                  _builder.append(_plusPlus_6, "\t");
                                  _builder.append(".val =  ");
                                  Values _pVal_19 = p.getPVal();
                                  String _function_5 = _pVal_19.getFunction();
                                  _builder.append(_function_5, "\t");
                                  _builder.newLineIfNotEmpty();
                                } else {
                                  Values _pVal_20 = p.getPVal();
                                  String _value_4 = _pVal_20.getValue();
                                  boolean _notEquals_12 = (!Objects.equal(_value_4, null));
                                  if (_notEquals_12) {
                                    _builder.append("\t");
                                    _builder.append("dose.0.solute.");
                                    _builder.append(count1, "\t");
                                    _builder.append(".property.");
                                    int _plusPlus_7 = count2++;
                                    _builder.append(_plusPlus_7, "\t");
                                    _builder.append(".val =  ");
                                    Values _pVal_21 = p.getPVal();
                                    String _value_5 = _pVal_21.getValue();
                                    _builder.append(_value_5, "\t");
                                    _builder.newLineIfNotEmpty();
                                  } else {
                                    Values _pVal_22 = p.getPVal();
                                    String _fvalue_4 = _pVal_22.getFvalue();
                                    boolean _notEquals_13 = (!Objects.equal(_fvalue_4, null));
                                    if (_notEquals_13) {
                                      _builder.append("\t");
                                      _builder.append("dose.0.solute.");
                                      _builder.append(count1, "\t");
                                      _builder.append(".property.");
                                      int _plusPlus_8 = count2++;
                                      _builder.append(_plusPlus_8, "\t");
                                      _builder.append(".val =  ");
                                      Values _pVal_23 = p.getPVal();
                                      String _fvalue_5 = _pVal_23.getFvalue();
                                      _builder.append(_fvalue_5, "\t");
                                      _builder.newLineIfNotEmpty();
                                    }
                                  }
                                }
                              }
                            }
                          } else {
                            String _pName_23 = p.getPName();
                            boolean _equals_17 = _pName_23.equals("metabolites");
                            if (_equals_17) {
                              _builder.newLine();
                              {
                                Design _expDesign = e.getExpDesign();
                                Variables _variables = _expDesign.getVariables();
                                IndependentVariables _independentVariables = _variables.getIndependentVariables();
                                EList<FactorLevels> _variables_1 = _independentVariables.getVariables();
                                boolean _notEquals_14 = (!Objects.equal(_variables_1, null));
                                if (_notEquals_14) {
                                  {
                                    Design _expDesign_1 = e.getExpDesign();
                                    Variables _variables_2 = _expDesign_1.getVariables();
                                    IndependentVariables _independentVariables_1 = _variables_2.getIndependentVariables();
                                    EList<FactorLevels> _variables_3 = _independentVariables_1.getVariables();
                                    for(final FactorLevels factorLevels : _variables_3) {
                                      {
                                        String _facName = factorLevels.getFacName();
                                        Values _pVal_24 = p.getPVal();
                                        String _function_6 = _pVal_24.getFunction();
                                        String[] _split = _function_6.split("-");
                                        Object _get = _split[0];
                                        boolean _equals_18 = _facName.equals(_get);
                                        if (_equals_18) {
                                          {
                                            String _l = factorLevels.getL();
                                            boolean _notEquals_15 = (!Objects.equal(_l, null));
                                            if (_notEquals_15) {
                                              _builder.append("\t");
                                              _builder.append("dose.0.solute.");
                                              _builder.append(count1, "\t");
                                              _builder.append(".property.");
                                              _builder.append(count2, "\t");
                                              _builder.append(".key = metabolites");
                                              _builder.newLineIfNotEmpty();
                                              _builder.append("\t");
                                              _builder.append("dose.0.solute.");
                                              _builder.append(count1, "\t");
                                              _builder.append(".property.");
                                              _builder.append(count2, "\t");
                                              _builder.append(".type = map");
                                              _builder.newLineIfNotEmpty();
                                              _builder.append("\t");
                                              _builder.append("dose.0.solute.");
                                              _builder.append(count1, "\t");
                                              _builder.append(".property.");
                                              int _plusPlus_9 = count2++;
                                              _builder.append(_plusPlus_9, "\t");
                                              _builder.append(".val =  ");
                                              Values _pVal_25 = p.getPVal();
                                              String _function_7 = _pVal_25.getFunction();
                                              String[] _split_1 = _function_7.split("-");
                                              String _get_1 = _split_1[1];
                                              _builder.append(_get_1, "\t");
                                              _builder.append(" => <");
                                              String _l_1 = factorLevels.getL();
                                              _builder.append(_l_1, "\t");
                                              _builder.append(">");
                                              _builder.newLineIfNotEmpty();
                                            } else {
                                              boolean _and = false;
                                              String _start1 = factorLevels.getStart1();
                                              boolean _notEquals_16 = (!Objects.equal(_start1, null));
                                              if (!_notEquals_16) {
                                                _and = false;
                                              } else {
                                                String _end1 = factorLevels.getEnd1();
                                                boolean _notEquals_17 = (!Objects.equal(_end1, null));
                                                _and = _notEquals_17;
                                              }
                                              if (_and) {
                                                _builder.append("\t");
                                                _builder.append("dose.0.solute.");
                                                _builder.append(count1, "\t");
                                                _builder.append(".property.");
                                                _builder.append(count2, "\t");
                                                _builder.append(".key = metabolites");
                                                _builder.newLineIfNotEmpty();
                                                _builder.append("\t");
                                                _builder.append("dose.0.solute.");
                                                _builder.append(count1, "\t");
                                                _builder.append(".property.");
                                                _builder.append(count2, "\t");
                                                _builder.append(".type = map");
                                                _builder.newLineIfNotEmpty();
                                                _builder.append("\t");
                                                _builder.append("dose.0.solute.");
                                                _builder.append(count1, "\t");
                                                _builder.append(".property.");
                                                int _plusPlus_10 = count2++;
                                                _builder.append(_plusPlus_10, "\t");
                                                _builder.append(".val =  ");
                                                Values _pVal_26 = p.getPVal();
                                                String _function_8 = _pVal_26.getFunction();
                                                String[] _split_2 = _function_8.split("-");
                                                String _get_2 = _split_2[1];
                                                _builder.append(_get_2, "\t");
                                                _builder.append(" => <");
                                                String _start1_1 = factorLevels.getStart1();
                                                _builder.append(_start1_1, "\t");
                                                _builder.append(",");
                                                String _end1_1 = factorLevels.getEnd1();
                                                _builder.append(_end1_1, "\t");
                                                _builder.append(">");
                                                _builder.newLineIfNotEmpty();
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                              _builder.append("\t\t\t\t\t\t");
                              _builder.newLine();
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    return _builder;
  }
  
  public CharSequence toKupfferCell(final ModelSection m) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("package ishc.model;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.lang.Math;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import sim.field.grid.*;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import sim.util.Bag;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public class KupfferCell extends Cell {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger( ISHC.class );");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public KupfferCell(Culture p, ec.util.MersenneTwisterFast random, int x, int y) {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("super(p,random);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("setLoc(x,y);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("actionShuffler.clear();         ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("actionShuffler.add(new Runnable() { public void run() { handleInflammation(); } });");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("actionShuffler.add(new Runnable() { public void run() { handleDegradation();}} );");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("BolusEntry cytokineBolusEntry = null;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public void handleInflammation()");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("int numInflammatoryStimuli = 0;");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("int numCytokines = 0;");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("for(Object o : solutes)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("Solute s = (Solute) o;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if(s.hasProperty(\"inflammatory\") && ((Boolean)s.getProperty(\"inflammatory\")))");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("numInflammatoryStimuli++;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if(s.type.equals(\"Cytokine\"))");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("numCytokines++;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("} ");
    _builder.newLine();
    {
      EList<Mechanism> _mechanisms = m.getMechanisms();
      for(final Mechanism mech : _mechanisms) {
        _builder.newLine();
        {
          boolean _and = false;
          Reaction _lHS = mech.getLHS();
          String _agent = _lHS.getAgent();
          boolean _notEquals = (!Objects.equal(_agent, null));
          if (!_notEquals) {
            _and = false;
          } else {
            Reaction _lHS_1 = mech.getLHS();
            String _agent1 = _lHS_1.getAgent1();
            boolean _notEquals_1 = (!Objects.equal(_agent1, null));
            _and = _notEquals_1;
          }
          if (_and) {
            _builder.newLine();
            {
              boolean _or = false;
              Reaction _lHS_2 = mech.getLHS();
              String _agent_1 = _lHS_2.getAgent();
              boolean _equalsIgnoreCase = _agent_1.equalsIgnoreCase("Kupffercells");
              if (_equalsIgnoreCase) {
                _or = true;
              } else {
                Reaction _lHS_3 = mech.getLHS();
                String _agent_2 = _lHS_3.getAgent();
                boolean _equalsIgnoreCase_1 = _agent_2.equalsIgnoreCase("Kupffercell");
                _or = _equalsIgnoreCase_1;
              }
              if (_or) {
                _builder.append("\t\t           \t\t ");
                _builder.append("if(s.type.equals(\"");
                Reaction _lHS_4 = mech.getLHS();
                String _agent1_1 = _lHS_4.getAgent1();
                _builder.append(_agent1_1, "\t\t           \t\t ");
                _builder.append("\"){");
                _builder.newLineIfNotEmpty();
                _builder.newLine();
                {
                  GuardCondition _condition = mech.getCondition();
                  boolean _notEquals_2 = (!Objects.equal(_condition, null));
                  if (_notEquals_2) {
                    _builder.append("if(\"");
                    GuardCondition _condition_1 = mech.getCondition();
                    String _condition1 = _condition_1.getCondition1();
                    _builder.append(_condition1, "");
                    _builder.append("\" ");
                    GuardCondition _condition_2 = mech.getCondition();
                    String _link = _condition_2.getLink();
                    _builder.append(_link, "");
                    _builder.append(" \"");
                    GuardCondition _condition_3 = mech.getCondition();
                    String _condition2 = _condition_3.getCondition2();
                    _builder.append(_condition2, "");
                    _builder.append("\")");
                    _builder.newLineIfNotEmpty();
                  }
                }
                {
                  Reaction _rHS = mech.getRHS();
                  String _agent1_2 = _rHS.getAgent1();
                  boolean _notEquals_3 = (!Objects.equal(_agent1_2, null));
                  if (_notEquals_3) {
                    {
                      boolean _or_1 = false;
                      Reaction _rHS_1 = mech.getRHS();
                      String _agent1_3 = _rHS_1.getAgent1();
                      boolean _equalsIgnoreCase_2 = _agent1_3.equalsIgnoreCase("Cytokines");
                      if (_equalsIgnoreCase_2) {
                        _or_1 = true;
                      } else {
                        Reaction _rHS_2 = mech.getRHS();
                        String _agent1_4 = _rHS_2.getAgent1();
                        boolean _equalsIgnoreCase_3 = _agent1_4.equalsIgnoreCase("Cytokine");
                        _or_1 = _equalsIgnoreCase_3;
                      }
                      if (_or_1) {
                        _builder.append("numCytokines++;\t  ");
                        _builder.newLine();
                      } else {
                        boolean _or_2 = false;
                        Reaction _rHS_3 = mech.getRHS();
                        String _agent1_5 = _rHS_3.getAgent1();
                        boolean _equalsIgnoreCase_4 = _agent1_5.equalsIgnoreCase("Inflammation");
                        if (_equalsIgnoreCase_4) {
                          _or_2 = true;
                        } else {
                          Reaction _rHS_4 = mech.getRHS();
                          String _agent1_6 = _rHS_4.getAgent1();
                          boolean _equalsIgnoreCase_5 = _agent1_6.equalsIgnoreCase("InflammatoryAgent");
                          _or_2 = _equalsIgnoreCase_5;
                        }
                        if (_or_2) {
                          _builder.append("numInflammatoryStimuli++;");
                          _builder.newLine();
                        } else {
                          boolean _or_3 = false;
                          Reaction _rHS_5 = mech.getRHS();
                          String _agent1_7 = _rHS_5.getAgent1();
                          boolean _equalsIgnoreCase_6 = _agent1_7.equalsIgnoreCase("No Inflammation");
                          if (_equalsIgnoreCase_6) {
                            _or_3 = true;
                          } else {
                            Reaction _rHS_6 = mech.getRHS();
                            String _agent1_8 = _rHS_6.getAgent1();
                            boolean _equalsIgnoreCase_7 = _agent1_8.equalsIgnoreCase("NoInflammation");
                            _or_3 = _equalsIgnoreCase_7;
                          }
                          if (_or_3) {
                            _builder.append("numInflammatoryStimuli--;");
                            _builder.newLine();
                          }
                        }
                      }
                    }
                  }
                }
                {
                  Reaction _rHS_7 = mech.getRHS();
                  String _agent_3 = _rHS_7.getAgent();
                  boolean _notEquals_4 = (!Objects.equal(_agent_3, null));
                  if (_notEquals_4) {
                    {
                      boolean _or_4 = false;
                      Reaction _rHS_8 = mech.getRHS();
                      String _agent_4 = _rHS_8.getAgent();
                      boolean _equals = _agent_4.equals("Cytokines");
                      if (_equals) {
                        _or_4 = true;
                      } else {
                        Reaction _rHS_9 = mech.getRHS();
                        String _agent_5 = _rHS_9.getAgent();
                        boolean _equals_1 = _agent_5.equals("Cytokine");
                        _or_4 = _equals_1;
                      }
                      if (_or_4) {
                        _builder.append(" ");
                        _builder.append("numCytokines++;\t  ");
                        _builder.newLine();
                      } else {
                        boolean _or_5 = false;
                        Reaction _rHS_10 = mech.getRHS();
                        String _agent_6 = _rHS_10.getAgent();
                        boolean _equalsIgnoreCase_8 = _agent_6.equalsIgnoreCase("Inflammation");
                        if (_equalsIgnoreCase_8) {
                          _or_5 = true;
                        } else {
                          Reaction _rHS_11 = mech.getRHS();
                          String _agent_7 = _rHS_11.getAgent();
                          boolean _equalsIgnoreCase_9 = _agent_7.equalsIgnoreCase("InflammatoryAgent");
                          _or_5 = _equalsIgnoreCase_9;
                        }
                        if (_or_5) {
                          _builder.append("numInflammatoryStimuli++;");
                          _builder.newLine();
                        } else {
                          boolean _or_6 = false;
                          Reaction _rHS_12 = mech.getRHS();
                          String _agent_8 = _rHS_12.getAgent();
                          boolean _equalsIgnoreCase_10 = _agent_8.equalsIgnoreCase("No Inflammation");
                          if (_equalsIgnoreCase_10) {
                            _or_6 = true;
                          } else {
                            Reaction _rHS_13 = mech.getRHS();
                            String _agent_9 = _rHS_13.getAgent();
                            boolean _equalsIgnoreCase_11 = _agent_9.equalsIgnoreCase("NoInflammation");
                            _or_6 = _equalsIgnoreCase_11;
                          }
                          if (_or_6) {
                            _builder.append("numInflammatoryStimuli--;");
                            _builder.newLine();
                          }
                        }
                      }
                    }
                  }
                }
                _builder.append("  \t");
                _builder.newLine();
                _builder.append("\t\t");
                _builder.newLine();
                _builder.newLine();
              }
            }
          }
        }
      }
    }
    _builder.append("\t            \t     ");
    _builder.newLine();
    _builder.append("\t            \t  ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if(numCytokines >= parent.cytokineThreshold)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if(numInflammatoryStimuli >= parent.inflammatoryStimulusThreshold)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("{               ");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("double probability = 1.0 - Math.exp(-1*(numInflammatoryStimuli - parent.inflammatoryStimulusThreshold) / parent.exponentialFactor);");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("double draw = rng.nextDouble();");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if(draw <= probability)");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("addCytokine();");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public Solute addCytokine()");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if(cytokineBolusEntry == null)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("sim.util.Bag bolusEntries = ((BolusDose) parent.model.delivery.doses.objs[0]).solution;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("for (int i = 0; i < bolusEntries.numObjs; i++) {");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("BolusEntry be = (BolusEntry) bolusEntries.objs[i];");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("if (be.tag.equals(\"Cytokine\")) {");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("cytokineBolusEntry = be;");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("//Create the Cytokine");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("Solute cytokine = new Solute(cytokineBolusEntry);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("cytokine.setProperties(cytokineBolusEntry.props);");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("//Add the Cytokine");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("parent.solutes.add(cytokine);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("parent.cellSpace.setObjectLocation(cytokine, myX, myY);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("solutes.add(cytokine);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("return cytokine;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence toHepatocyte(final ModelSection m) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("package ishc.model;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.HashMap;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import java.util.LinkedHashMap;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import sim.util.Bag;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("import sim.util.Double2D;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public class Hepatocyte extends Cell implements CellInfo, EIInfo, ELInfo, MetabolismInfo {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger( ISHC.class );");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("HashMap<String, Double> metProbMap = new LinkedHashMap<String,Double>();");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("HashMap<String, HashMap<String,Double>> productionMap = new LinkedHashMap<String,HashMap<String,Double>>();");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("int numEnzymesAtInit = -Integer.MAX_VALUE;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public Hepatocyte(Culture p, ec.util.MersenneTwisterFast random, int x, int y) {");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("super(p, random);");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("setLoc(x,y);");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if (parent.ei_rate > 0.0) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("actionShuffler.add(new EIHandler((CellInfo) this, (BindingInfo) this, (EIInfo) this, log));");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if (parent.el_rate > 0.0) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("actionShuffler.add(new ELHandler((CellInfo) this, (BindingInfo) this, (ELInfo) this, log));");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if (parent.useDDI) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("actionShuffler.add(new DDIHandler((BindingInfo) this, rng, log, parent.pReplace));");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}       ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if (parent.drRate > 0) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("actionShuffler.add(new Runnable() { public void run() { handleDownRegulation(); } });");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("float ENZYME_INIT_FACTOR = 3.0f;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public void init() {    ");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("int min = StrictMath.round(parent.bindmin);");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("int max = StrictMath.round(parent.bindmax);");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("numEnzymesAtInit = rng.nextInt(max-min) + min;");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("} catch (IllegalArgumentException e) {");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("numEnzymesAtInit = min;");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("}    ");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("for (int bNdx=0 ; bNdx<numEnzymesAtInit; bNdx++) ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("binders.add(new Enzyme());");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("for (Object o : ((BolusDose)parent.model.delivery.doses.objs[0]).solution) {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("BolusEntry be = (BolusEntry) o;");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if (be.bindable) {");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("double mps = (Double)be.props.get(\"metProbStart\");");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("double mpf = (Double)be.props.get(\"metProbFinish\");          ");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("double mp = mps + (mpf-mps)*0.5;");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("metProbMap.put(be.tag, mp);");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("HashMap<String,Double2D> mprodmap = (HashMap<String,Double2D>) be.props.get(\"metabolites\");");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("HashMap<String,Double> metsMap = new LinkedHashMap<>();");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("for (java.util.Map.Entry<String,Double2D> me : mprodmap.entrySet()) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("Double2D d2d = me.getValue();");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("double prmin = d2d.x;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("double prmax = d2d.y;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("double prodRate = prmin + (prmax-prmin)*0.5;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("metsMap.put(me.getKey(), prodRate);");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t          ");
    _builder.append("productionMap.put(be.tag,metsMap);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t      ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if (!metProbMap.isEmpty()) {");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("actionShuffler.add(new MetabolismHandler((BindingInfo) this, (MetabolismInfo) this, rng, log));");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public java.util.ArrayList<ishc.util.MyInt> elimQueue = null;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("int rate_increment = parent.drRate;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public void handleDownRegulation()");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("{      ");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("boolean thereIsACytokine = false;");
    _builder.newLine();
    {
      EList<Mechanism> _mechanisms = m.getMechanisms();
      for(final Mechanism mech : _mechanisms) {
        {
          boolean _and = false;
          Reaction _lHS = mech.getLHS();
          String _agent = _lHS.getAgent();
          boolean _notEquals = (!Objects.equal(_agent, null));
          if (!_notEquals) {
            _and = false;
          } else {
            Reaction _lHS_1 = mech.getLHS();
            String _agent1 = _lHS_1.getAgent1();
            boolean _notEquals_1 = (!Objects.equal(_agent1, null));
            _and = _notEquals_1;
          }
          if (_and) {
            {
              boolean _or = false;
              Reaction _lHS_2 = mech.getLHS();
              String _agent1_1 = _lHS_2.getAgent1();
              boolean _equalsIgnoreCase = _agent1_1.equalsIgnoreCase("Hepatocyte");
              if (_equalsIgnoreCase) {
                _or = true;
              } else {
                Reaction _lHS_3 = mech.getLHS();
                String _agent_1 = _lHS_3.getAgent();
                boolean _equalsIgnoreCase_1 = _agent_1.equalsIgnoreCase("Hepatocyte");
                _or = _equalsIgnoreCase_1;
              }
              if (_or) {
                {
                  boolean _and_1 = false;
                  Reaction _rHS = mech.getRHS();
                  String _agent1_2 = _rHS.getAgent1();
                  boolean _notEquals_2 = (!Objects.equal(_agent1_2, null));
                  if (!_notEquals_2) {
                    _and_1 = false;
                  } else {
                    boolean _or_1 = false;
                    Reaction _rHS_1 = mech.getRHS();
                    String _agent1_3 = _rHS_1.getAgent1();
                    boolean _equalsIgnoreCase_2 = _agent1_3.equalsIgnoreCase("Cytokines");
                    if (_equalsIgnoreCase_2) {
                      _or_1 = true;
                    } else {
                      Reaction _rHS_2 = mech.getRHS();
                      String _agent1_4 = _rHS_2.getAgent1();
                      boolean _equalsIgnoreCase_3 = _agent1_4.equalsIgnoreCase("Cytokine");
                      _or_1 = _equalsIgnoreCase_3;
                    }
                    _and_1 = _or_1;
                  }
                  if (_and_1) {
                    {
                      GuardCondition _condition = mech.getCondition();
                      boolean _notEquals_3 = (!Objects.equal(_condition, null));
                      if (_notEquals_3) {
                        _builder.append("if(\"");
                        GuardCondition _condition_1 = mech.getCondition();
                        String _condition1 = _condition_1.getCondition1();
                        _builder.append(_condition1, "");
                        _builder.append("\" ");
                        GuardCondition _condition_2 = mech.getCondition();
                        String _link = _condition_2.getLink();
                        _builder.append(_link, "");
                        _builder.append(" \"");
                        GuardCondition _condition_3 = mech.getCondition();
                        String _condition2 = _condition_3.getCondition2();
                        _builder.append(_condition2, "");
                        _builder.append("\"){");
                        _builder.newLineIfNotEmpty();
                        _builder.append("\t");
                        _builder.append("thereIsACytokine = true;");
                        _builder.newLine();
                        _builder.append("\t");
                        _builder.append("}");
                        _builder.newLine();
                      }
                    }
                  } else {
                    _builder.append("for(Solute s : solutes)");
                    _builder.newLine();
                    _builder.append("{");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("if(s.type.equalsIgnoreCase(\"Cytokine\"))");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("{");
                    _builder.newLine();
                    _builder.append("        ");
                    _builder.append("thereIsACytokine = true;");
                    _builder.newLine();
                    _builder.append("        ");
                    _builder.append("break;");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("}");
                    _builder.newLine();
                    _builder.append("}");
                    _builder.newLine();
                  }
                }
                {
                  boolean _and_2 = false;
                  Reaction _rHS_3 = mech.getRHS();
                  String _agent1_5 = _rHS_3.getAgent1();
                  boolean _notEquals_4 = (!Objects.equal(_agent1_5, null));
                  if (!_notEquals_4) {
                    _and_2 = false;
                  } else {
                    boolean _or_2 = false;
                    Reaction _rHS_4 = mech.getRHS();
                    String _agent1_6 = _rHS_4.getAgent1();
                    boolean _equalsIgnoreCase_4 = _agent1_6.equalsIgnoreCase("Enzymes");
                    if (_equalsIgnoreCase_4) {
                      _or_2 = true;
                    } else {
                      Reaction _rHS_5 = mech.getRHS();
                      String _agent1_7 = _rHS_5.getAgent1();
                      boolean _equalsIgnoreCase_5 = _agent1_7.equalsIgnoreCase("Enzyme");
                      _or_2 = _equalsIgnoreCase_5;
                    }
                    _and_2 = _or_2;
                  }
                  if (_and_2) {
                    {
                      GuardCondition _condition_4 = mech.getCondition();
                      boolean _notEquals_5 = (!Objects.equal(_condition_4, null));
                      if (_notEquals_5) {
                        _builder.append("if(\"");
                        GuardCondition _condition_5 = mech.getCondition();
                        String _condition1_1 = _condition_5.getCondition1();
                        _builder.append(_condition1_1, "");
                        _builder.append("\" ");
                        GuardCondition _condition_6 = mech.getCondition();
                        String _link_1 = _condition_6.getLink();
                        _builder.append(_link_1, "");
                        _builder.append(" \"");
                        GuardCondition _condition_7 = mech.getCondition();
                        String _condition2_1 = _condition_7.getCondition2();
                        _builder.append(_condition2_1, "");
                        _builder.append("\"){");
                        _builder.newLineIfNotEmpty();
                        _builder.append("\t\t         \t\t\t");
                        _builder.append("binders.add(new Enzyme());");
                        _builder.newLine();
                        _builder.append("\t\t            \t\t");
                        _builder.append("return;");
                        _builder.newLine();
                        _builder.append("\t\t            \t");
                        _builder.append("}");
                        _builder.newLine();
                      }
                    }
                  } else {
                    _builder.append(" ");
                    _builder.append("if(binders.size() < numEnzymesAtInit && elimQueue != null && elimQueue.size() == 0 && !thereIsACytokine)");
                    _builder.newLine();
                    _builder.append("{            ");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("if(rng.nextDouble() < parent.drReplenish)");
                    _builder.newLine();
                    _builder.append("        ");
                    _builder.append("binders.add(new Enzyme());");
                    _builder.newLine();
                    _builder.append("    ");
                    _builder.append("return;");
                    _builder.newLine();
                    _builder.append("}");
                    _builder.newLine();
                  }
                }
                _builder.append("if(elimQueue != null && elimQueue.size() > 0)");
                _builder.newLine();
                _builder.append("{");
                _builder.newLine();
                _builder.append("    ");
                _builder.append("int num_to_elim = (int) elimQueue.remove(0).val;");
                _builder.newLine();
                _builder.append("    ");
                _builder.append("java.util.ArrayList<Binder> to_be_removed = new java.util.ArrayList<Binder>();");
                _builder.newLine();
                _builder.append("    ");
                _builder.append("for(Binder b : binders)");
                _builder.newLine();
                _builder.append("    ");
                _builder.append("{");
                _builder.newLine();
                _builder.append("        ");
                _builder.append("if(num_to_elim <= 0)");
                _builder.newLine();
                _builder.append("            ");
                _builder.append("break;");
                _builder.newLine();
                _builder.append("        ");
                _builder.append("if(!bound.containsKey(b)) //if unbound");
                _builder.newLine();
                _builder.append("            ");
                _builder.append("to_be_removed.add(b);");
                _builder.newLine();
                _builder.append("        ");
                _builder.append("if(to_be_removed.size() >= num_to_elim)");
                _builder.newLine();
                _builder.append("            ");
                _builder.append("break;");
                _builder.newLine();
                {
                  Reaction _rHS_6 = mech.getRHS();
                  String _agent1_8 = _rHS_6.getAgent1();
                  boolean _contains = _agent1_8.contains("Removed");
                  if (_contains) {
                    _builder.append("        ");
                    _builder.append("if(!bound.containsKey(\"");
                    Reaction _rHS_7 = mech.getRHS();
                    String _agent1_9 = _rHS_7.getAgent1();
                    Reaction _rHS_8 = mech.getRHS();
                    String _agent1_10 = _rHS_8.getAgent1();
                    int _indexOf = _agent1_10.indexOf("Removed");
                    String _substring = _agent1_9.substring(_indexOf);
                    _builder.append(_substring, "        ");
                    _builder.append("\")) //if unbound");
                    _builder.newLineIfNotEmpty();
                    _builder.append("        ");
                    _builder.append("    ");
                    _builder.append("to_be_removed.add(b);");
                    _builder.newLine();
                  }
                }
                {
                  Reaction _rHS_9 = mech.getRHS();
                  String _agent1_11 = _rHS_9.getAgent1();
                  boolean _contains_1 = _agent1_11.contains("Added");
                  if (_contains_1) {
                    _builder.append("        ");
                    _builder.append("if(!bound.containsKey(\"");
                    Reaction _rHS_10 = mech.getRHS();
                    String _agent1_12 = _rHS_10.getAgent1();
                    Reaction _rHS_11 = mech.getRHS();
                    String _agent1_13 = _rHS_11.getAgent1();
                    int _indexOf_1 = _agent1_13.indexOf("Added");
                    String _substring_1 = _agent1_12.substring(_indexOf_1);
                    _builder.append(_substring_1, "        ");
                    _builder.append(")\") //if unbound");
                    _builder.newLineIfNotEmpty();
                    _builder.append("        ");
                    _builder.append("    ");
                    _builder.append("to_be_removed.remove(b);");
                    _builder.newLine();
                  }
                }
              }
            }
          }
        }
      }
    }
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t ");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("for(Binder b : to_be_removed)");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("binders.remove(b);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("Binder firstUnbound = null;");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("for(Binder b : binders)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if(!bound.containsKey(b))");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("firstUnbound = b;");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("if(firstUnbound == null)");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("return;                ");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("for(Solute s : solutes)");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("if(s.type.equalsIgnoreCase(\"Cytokine\"))");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("if(rng.nextDouble() < parent.drRemove)");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("//Add to the queue to be removed, then return");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("if(elimQueue == null)");
    _builder.newLine();
    _builder.append("\t                        ");
    _builder.append("elimQueue = new java.util.ArrayList<ishc.util.MyInt>();");
    _builder.newLine();
    _builder.append("\t                                        ");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("for(int i = 0; i < rate_increment - 1; i++)");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("{");
    _builder.newLine();
    _builder.append("\t                        ");
    _builder.append("elimQueue.add(new ishc.util.MyInt(0));");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("elimQueue.add(new ishc.util.MyInt(1));");
    _builder.newLine();
    _builder.append("\t                    ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("\t                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("//Implementations for CellInfo");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public double getResources() {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("return parent.resources;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public int getBindmax() {return parent.bindmax;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public int getNumEnzymesAtInit() {return numEnzymesAtInit; }");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("//Implementations for EIInfo");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public int getEIThresh() {return parent.ei_thresh;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public double getEIRate() {return parent.ei_rate;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public double getEIResponse() {return parent.ei_response_factor;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("//Implementations for ELInfo");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public int getELThresh() {return parent.el_thresh;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public double getELRate() {return parent.el_rate;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public double getELResponse() {return parent.el_response_factor;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("//Implementations for MetabolismInfo");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public HashMap<String, Double> getMetProbMap() {return metProbMap;}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public HashMap<String, HashMap<String,Double>> getProductionMap() {return productionMap; }");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public Bag getBolusEntries() {return ((BolusDose) parent.model.delivery.doses.objs[0]).solution; }");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public void removeSolute(Solute s) {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("solutes.remove(s);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("parent.solutes.remove(s);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("parent.cellSpace.remove(s);");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("public void addSolute(Solute s) {");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("parent.solutes.add(s);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("parent.cellSpace.setObjectLocation(s, myX, myY);");
    _builder.newLine();
    _builder.append("\t        ");
    _builder.append("solutes.add(s);");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
