/**
 * generated by Xtext
 */
package org.xtext.DOE.validation;

import org.xtext.DOE.validation.AbstractExperimentOntologyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ExperimentOntologyValidator extends AbstractExperimentOntologyValidator {
}
