/*
 * generated by Xtext
 */
package org.xtext.DOE.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExperimentOntologyUiModule extends org.xtext.DOE.ui.AbstractExperimentOntologyUiModule {
	public ExperimentOntologyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
